import type { AuditLog, Contract, Dispute, Job, Message, Milestone, Notification, Proposal, Review, Service, Transaction, User } from "./types";

export const demoUsers: User[] = [
  { id: "u_client", name: "Minh Labs", email: "client@aitasker.dev", password: "demo1234", role: "client", avatar: "ML", title: "Product Owner", company: "Minh Labs Co.", trustScore: 88, walletBalance: 5000, location: "TP.HCM", language: "vi", phone: "0901000001", createdAt: "2026-06-01" },
  { id: "u_expert", name: "An Trần", email: "expert@aitasker.dev", password: "demo1234", role: "expert", avatar: "AT", title: "RAG / LLM Engineer", verified: true, trustScore: 96, walletBalance: 1200, totalEarnings: 8400, hourlyRate: 85, skills: ["LangChain", "Vector DB", "Python", "FastAPI"], bio: "3 năm triển khai RAG production cho doanh nghiệp Việt Nam, mạnh về citation grounding, eval harness và bàn giao bảo mật.", portfolioUrls: ["RAG banking assistant", "Legal search copilot", "Internal knowledge chatbot"], linkedinUrl: "https://linkedin.com/in/an-tran-ai", githubUrl: "https://github.com/antran-ai", location: "Hà Nội", language: "vi", createdAt: "2026-06-01" },
  { id: "u_enterprise", name: "Nova Enterprise", email: "enterprise@aitasker.dev", password: "demo1234", role: "enterprise", avatar: "NE", title: "AI Program Office", company: "Nova Corp", enterpriseId: "ent_nova", trustScore: 91, walletBalance: 20000, location: "Đà Nẵng", language: "vi", createdAt: "2026-06-01" },
  { id: "u_admin", name: "AITasker Admin", email: "admin@aitasker.dev", password: "demo1234", role: "admin", avatar: "AO", title: "Quản trị viên hệ thống", verified: true, trustScore: 100, walletBalance: 0, createdAt: "2026-06-01" },
  { id: "u_expert2", name: "Nguyễn Linh", email: "linh.cv@aitasker.dev", password: "demo1234", role: "expert", avatar: "NL", title: "Computer Vision Engineer", verified: true, trustScore: 93, hourlyRate: 70, walletBalance: 900, totalEarnings: 6200, skills: ["YOLO", "OpenCV", "PyTorch", "TensorFlow", "Data Labeling"], bio: "5 năm kinh nghiệm CV cho sản xuất & bán lẻ. Đã triển khai 12 mô hình production.", portfolioUrls: ["Defect detection factory", "Retail shelf analytics", "Face attendance system"], linkedinUrl: "https://linkedin.com/in/nguyen-linh-cv", githubUrl: "https://github.com/linh-cv", createdAt: "2026-06-03" },
  { id: "u_expert3", name: "Trần Quang Huy", email: "huy.mlops@aitasker.dev", password: "demo1234", role: "expert", avatar: "QH", title: "MLOps & AI Infrastructure Engineer", verified: false, trustScore: 85, hourlyRate: 90, walletBalance: 400, totalEarnings: 4100, skills: ["Docker", "Kubernetes", "GitHub Actions", "MLflow", "PromptOps"], bio: "Thiết kế hạ tầng MLOps, CI/CD, monitoring và rollout an toàn cho mô hình AI.", portfolioUrls: ["MLflow enterprise template", "PromptOps CI", "Kubernetes GPU serving"], githubUrl: "https://github.com/huy-mlops", createdAt: "2026-06-06" },
  { id: "u_expert4", name: "Phạm Thị Mai", email: "mai.nlp@aitasker.dev", password: "demo1234", role: "expert", avatar: "PM", title: "NLP Engineer — Vietnamese Language Specialist", verified: true, trustScore: 90, hourlyRate: 65, walletBalance: 720, totalEarnings: 5300, skills: ["PhoBERT", "HuggingFace", "FastAPI", "Text Classification", "Named Entity Recognition"], bio: "Chuyên xử lý tiếng Việt: phân loại văn bản, NER, OCR hậu xử lý và đánh giá mô hình NLP.", portfolioUrls: ["PhoBERT sentiment", "Vietnamese NER dataset", "Legal classifier"], createdAt: "2026-06-07" },
  { id: "u_expert5", name: "Lê Đức Anh", email: "anh.agent@aitasker.dev", password: "demo1234", role: "expert", avatar: "DA", title: "AI Agent Developer & Process Automation", verified: true, trustScore: 88, hourlyRate: 80, walletBalance: 650, totalEarnings: 3900, skills: ["LangGraph", "AutoGPT", "n8n", "Make.com", "Zapier", "Node.js"], bio: "Xây dựng AI Agent tự động hóa quy trình kinh doanh, social media, CRM và chăm sóc khách hàng.", portfolioUrls: ["Social media agent", "CRM follow-up bot", "Ops automation playbook"], createdAt: "2026-06-08" },
  { id: "u_client2", name: "Hoàng Văn Minh", email: "minh.shop@aitasker.dev", password: "demo1234", role: "client", avatar: "HM", title: "Founder & CEO", company: "Minh Fashion Store", trustScore: 84, walletBalance: 3000, location: "Biên Hòa", createdAt: "2026-06-09" },
  { id: "u_client3", name: "Trần Thị Hương", email: "huong.logistics@aitasker.dev", password: "demo1234", role: "client", avatar: "TH", title: "CTO / Product Lead", company: "FastMove Logistics", trustScore: 87, walletBalance: 8000, location: "Bình Dương", createdAt: "2026-06-10" },
  { id: "u_client4", name: "GreenFarm AI", email: "greenfarm@aitasker.dev", password: "demo1234", role: "client", avatar: "GF", title: "AgriTech Product Team", company: "GreenFarm", trustScore: 81, walletBalance: 4200, createdAt: "2026-06-11" },
  { id: "u_client5", name: "Saigon Media Hub", email: "mediahub@aitasker.dev", password: "demo1234", role: "client", avatar: "SM", title: "Marketing Lead", company: "Saigon Media Hub", trustScore: 83, walletBalance: 2500, createdAt: "2026-06-12" },
];

export const demoJobs: Job[] = [
  { id: "job_ecom_ai", title: "Xây dựng website bán hàng thời trang tích hợp AI gợi ý sản phẩm", clientId: "u_client2", category: "AI/E-commerce", budget: 3500, duration: "4 tuần", level: "Pro", status: "open", description: "Cần xây dựng website bán quần áo thời trang có tính năng AI gợi ý outfit theo lịch sử mua hàng, lọc theo màu sắc/size tự động, chatbot tư vấn 24/7.", skills: ["Next.js", "Recommendation System", "Python", "MongoDB"], proposals: ["prop_002", "prop_011"], createdAt: "2026-06-18", aiBrief: "Ưu tiên recommendation engine nhẹ, chatbot tư vấn, dashboard tracking CTR và conversion.", currency: "USD", isRemote: true },
  { id: "job_logistics_chatbot", title: "Chatbot chăm sóc khách hàng tự động cho sàn logistics", clientId: "u_client3", category: "LLM / RAG", budget: 4800, duration: "5 tuần", level: "Pro", status: "open", description: "Tích hợp chatbot AI vào Zalo OA và website để tự động tra cứu đơn hàng, xử lý khiếu nại cơ bản, chuyển tiếp agent thật khi cần. Cần kết nối với hệ thống ERP nội bộ qua API.", skills: ["LangChain", "GPT-4", "Webhook", "Zalo API"], proposals: ["prop_001", "prop_006"], createdAt: "2026-06-19", aiBrief: "RAG trên tài liệu hỗ trợ, workflow handoff, tracking ticket và guardrails bảo mật.", enterpriseId: "ent_nova", currency: "USD", isRemote: true },
  { id: "job_fraud_ml", title: "Hệ thống phát hiện gian lận giao dịch real-time bằng ML", clientId: "u_enterprise", enterpriseId: "ent_nova", category: "ML / Fraud Detection", budget: 9200, duration: "8 tuần", level: "Enterprise", status: "pending_approval", description: "Xây pipeline phát hiện bất thường theo thời gian thực với feature store, Kafka stream, dashboard cảnh báo và rule fallback.", skills: ["XGBoost", "Kafka", "Redis", "FastAPI", "Grafana"], proposals: ["prop_012"], createdAt: "2026-06-20", aiBrief: "Cần duyệt bảo mật dữ liệu trước khi phát hành ra marketplace.", currency: "USD", isRemote: true },
  { id: "job_ocr_invoice", title: "Fine-tune mô hình OCR nhận dạng hóa đơn tiếng Việt", clientId: "u_client", category: "NLP / OCR", budget: 2800, duration: "3 tuần", level: "Pro", status: "open", description: "Fine-tune OCR cho hóa đơn VAT tiếng Việt, hậu xử lý field extraction và đóng gói API để tích hợp vào hệ thống kế toán.", skills: ["TrOCR", "PaddleOCR", "Python", "FastAPI"], proposals: ["prop_003", "prop_014"], createdAt: "2026-06-21", aiBrief: "Tập trung accuracy với scan mờ, seal/con dấu và tài liệu hướng dẫn API.", currency: "USD", isRemote: true },
  { id: "job_social_agent", title: "Xây dựng AI Agent tự động đăng bài Facebook/Instagram cho SME", clientId: "u_client2", category: "AI Agent", budget: 1800, duration: "2 tuần", level: "Starter", status: "open", description: "Agent tạo lịch nội dung, sinh caption, đề xuất hình ảnh Canva và đăng bài qua Meta API theo quy trình duyệt nội bộ.", skills: ["LangGraph", "Meta API", "Canva API", "Python"], proposals: ["prop_005"], createdAt: "2026-06-22", aiBrief: "Luồng duyệt nội dung trước khi đăng là yêu cầu bắt buộc.", currency: "USD", isRemote: true },
  { id: "job_sales_insight", title: "Dashboard phân tích dữ liệu bán hàng với AI insight tự động", clientId: "u_client", category: "Data Analytics / AI", budget: 4100, duration: "4 tuần", level: "Pro", status: "open", description: "Tổng hợp dữ liệu POS/e-commerce, tự động phát hiện biến động doanh thu và sinh insight bằng AI hằng ngày.", skills: ["Python", "Pandas", "Plotly", "OpenAI API", "Next.js"], proposals: ["prop_007"], createdAt: "2026-06-23", aiBrief: "Cần dashboard realtime, mô hình phát hiện bất thường và summary bằng tiếng Việt.", currency: "USD", isRemote: true },
  { id: "job_legal_summary", title: "Hệ thống tóm tắt văn bản pháp lý tự động (Legal AI)", clientId: "u_enterprise", enterpriseId: "ent_nova", category: "LLM / Legal", budget: 6500, duration: "6 tuần", level: "Enterprise", status: "pending_approval", description: "Xây RAG/tóm tắt văn bản pháp lý tiếng Việt, trích dẫn điều khoản và review workflow trước khi xuất báo cáo.", skills: ["RAG", "LangChain", "Vietnamese NLP", "Vector DB"], proposals: [], createdAt: "2026-06-24", aiBrief: "Pending approval do liên quan dữ liệu pháp lý nhạy cảm.", currency: "USD", isRemote: true },
  { id: "job_face_attendance", title: "Nhận diện khuôn mặt và chấm công tự động cho nhà máy", clientId: "u_client3", category: "Computer Vision", budget: 5000, duration: "5 tuần", level: "Pro", status: "open", description: "Nhận diện nhân viên qua camera cổng vào, chống spoofing cơ bản, đồng bộ attendance sang HRM.", skills: ["FaceNet", "InsightFace", "OpenCV", "FastAPI", "React"], proposals: ["prop_004", "prop_010"], createdAt: "2026-06-25", aiBrief: "Cần demo với camera RTSP và báo cáo false positive/negative.", currency: "USD", isRemote: true },
  { id: "job_stock_signal", title: "Bot giao dịch chứng khoán semi-automatic với AI signal", clientId: "u_client", category: "AI / FinTech", budget: 7800, duration: "7 tuần", level: "Enterprise", status: "draft", description: "Bot phân tích chỉ báo kỹ thuật và tin tức để đưa signal bán/tạm giữ. Không tự động đặt lệnh khi chưa có xác nhận người dùng.", skills: ["Python", "TA-Lib", "LLM", "Backtrader", "Telegram Bot"], proposals: [], createdAt: "2026-06-26", aiBrief: "Cần kiểm duyệt rủi ro pháp lý trước khi public.", currency: "USD", isRemote: true },
  { id: "job_mlops_pipeline", title: "Dịch vụ MLOps: setup pipeline CI/CD cho team AI 10 người", clientId: "u_enterprise", enterpriseId: "ent_nova", category: "MLOps", budget: 5500, duration: "4 tuần", level: "Enterprise", status: "open", description: "Thiết lập model registry, experiment tracking, DVC, CI/CD và chuẩn rollout model cho team AI nội bộ.", skills: ["MLflow", "DVC", "GitHub Actions", "Docker", "Weights&Biases"], proposals: ["prop_008"], createdAt: "2026-06-27", aiBrief: "Có thể chia theo sprint: audit, pipeline, training, handover.", currency: "USD", isRemote: true },
  { id: "job_ner_dataset", title: "Tạo bộ dataset tiếng Việt cho bài toán Named Entity Recognition", clientId: "u_client", category: "Data & Annotation", budget: 1500, duration: "2 tuần", level: "Starter", status: "open", description: "Cần guideline, annotation tool setup và QA cho dataset NER tiếng Việt theo domain bán lẻ.", skills: ["Label Studio", "Python", "Doccano", "Vietnamese NLP"], proposals: ["prop_009"], createdAt: "2026-06-28", aiBrief: "Cần quy trình review 2 lớp để giảm label noise.", currency: "USD", isRemote: true },
  { id: "job_hr_chatbot", title: "Chatbot tuyển dụng tự động sàng lọc CV và phỏng vấn vòng 1", clientId: "u_enterprise", enterpriseId: "ent_nova", category: "HR AI / LLM", budget: 3800, duration: "3 tuần", level: "Pro", status: "open", description: "Chatbot đọc CV, chấm mức phù hợp, hỏi vòng 1 theo JD và gửi summary cho HR.", skills: ["LangChain", "GPT-4", "PDF parsing", "REST API"], proposals: ["prop_013"], createdAt: "2026-06-29", aiBrief: "Cần bias mitigation và log quyết định rõ ràng.", currency: "USD", isRemote: true },
  { id: "job_plant_mobile", title: "App mobile AI nhận diện bệnh cây trồng qua ảnh chụp", clientId: "u_client4", category: "Computer Vision / AgriTech", budget: 4200, duration: "5 tuần", level: "Pro", status: "in_progress", description: "Mobile app nhận diện bệnh lá cây, lưu lịch sử ảnh và đề xuất xử lý bằng tiếng Việt.", skills: ["EfficientNet", "React Native", "FastAPI", "Firebase"], proposals: ["prop_015"], createdAt: "2026-06-15", aiBrief: "Đang chạy contract sprint 1.", currency: "USD", isRemote: true },
  { id: "job_movie_recommend", title: "Hệ thống recommend phim/series cho OTT platform nội địa", clientId: "u_enterprise", enterpriseId: "ent_nova", category: "Recommendation System", budget: 8000, duration: "8 tuần", level: "Enterprise", status: "open", description: "Recommendation engine dựa trên watch history, cold-start user, A/B test và dashboard theo cohort.", skills: ["Collaborative Filtering", "Python", "Redis", "Airflow"], proposals: [], createdAt: "2026-06-17", aiBrief: "Cần chiến lược cold-start và realtime feature refresh.", currency: "USD", isRemote: true },
  { id: "job_voice_iot", title: "Tích hợp AI voice assistant tiếng Việt vào thiết bị IoT", clientId: "u_client3", category: "NLP / Voice AI", budget: 6000, duration: "6 tuần", level: "Enterprise", status: "open", description: "Voice assistant tiếng Việt điều khiển thiết bị qua MQTT, chạy trên Raspberry Pi, có fallback offline commands.", skills: ["Whisper", "TTS", "Rasa", "MQTT", "Raspberry Pi"], proposals: [], createdAt: "2026-06-16", aiBrief: "Cần test latency trên edge device và câu lệnh tiếng Việt.", currency: "USD", isRemote: true },
  { id: "job_support_ticket", title: "Phân loại ticket hỗ trợ khách hàng bằng AI tiếng Việt", clientId: "u_client", category: "NLP / Classification", budget: 2200, duration: "3 tuần", level: "Starter", status: "open", description: "Tự động phân loại ticket vào 8 nhóm, gợi ý mức ưu tiên và route sang team phụ trách.", skills: ["PhoBERT", "FastAPI", "Text Classification"], proposals: [], createdAt: "2026-06-14", aiBrief: "Ưu tiên precision cho nhóm khiếu nại khẩn cấp.", currency: "USD", isRemote: true },
  { id: "job_video_summary", title: "Tóm tắt video đào tạo nội bộ thành checklist hành động", clientId: "u_enterprise", enterpriseId: "ent_nova", category: "Multimodal AI", budget: 4700, duration: "4 tuần", level: "Pro", status: "open", description: "Upload video đào tạo, trích transcript, tóm tắt theo chương và sinh checklist học tập cho nhân viên.", skills: ["Whisper", "LLM", "Next.js", "S3"], proposals: [], createdAt: "2026-06-13", aiBrief: "Cần phân quyền tài liệu nội bộ và export PDF.", currency: "USD", isRemote: true },
  { id: "job_price_forecast", title: "Dự báo nhu cầu và giá tồn kho cho chuỗi bán lẻ", clientId: "u_client2", category: "Forecasting", budget: 5200, duration: "5 tuần", level: "Pro", status: "open", description: "Forecast demand theo SKU/store, cảnh báo tồn kho và đề xuất markdown price theo mùa.", skills: ["Prophet", "XGBoost", "Pandas", "PowerBI"], proposals: [], createdAt: "2026-06-12", aiBrief: "Cần model explainability cho buyer team.", currency: "USD", isRemote: true },
  { id: "job_quality_voice", title: "AI đánh giá chất lượng cuộc gọi tổng đài", clientId: "u_client3", category: "Speech Analytics", budget: 4400, duration: "4 tuần", level: "Pro", status: "open", description: "Speech-to-text tiếng Việt, scoring theo checklist CSKH, phát hiện sentiment và cảnh báo cuộc gọi rủi ro.", skills: ["Whisper", "Sentiment Analysis", "FastAPI", "Dashboard"], proposals: [], createdAt: "2026-06-11", aiBrief: "Cần bảo mật PII và redaction tự động.", currency: "USD", isRemote: true },
  { id: "job_doc_redaction", title: "Tự động che thông tin nhạy cảm trong tài liệu PDF", clientId: "u_enterprise", enterpriseId: "ent_nova", category: "Document AI / Security", budget: 3600, duration: "3 tuần", level: "Pro", status: "open", description: "Phát hiện và che số CCCD, số điện thoại, email, tài khoản ngân hàng trong PDF scan và PDF text.", skills: ["OCR", "NER", "PDF", "Security"], proposals: [], createdAt: "2026-06-10", aiBrief: "Cần review thủ công trước khi export bản final.", currency: "USD", isRemote: true },
];

export const demoProposals: Proposal[] = [
  { id: "prop_001", jobId: "job_logistics_chatbot", expertId: "u_expert", rate: 4300, eta: "24 ngày", status: "shortlisted", score: 95, createdAt: "2026-06-20", coverLetter: "Tôi đã xây dựng 3 hệ thống RAG production cho doanh nghiệp Việt Nam với 10k+ document, sử dụng Weaviate + LangChain. Điểm recall@5 đạt >88% trên bộ test nội bộ. Tôi có thể bắt đầu ngay và giao milestone đầu tiên trong 5 ngày." },
  { id: "prop_002", jobId: "job_ecom_ai", expertId: "u_expert2", rate: 3200, eta: "26 ngày", status: "sent", score: 86, createdAt: "2026-06-19", coverLetter: "Có kinh nghiệm 4 năm phát triển website thương mại điện tử với AI integration. Đã làm recommendation engine cho Shopee seller với CTR tăng 23%. Tôi sẽ demo luồng outfit recommendation trong tuần đầu." },
  { id: "prop_003", jobId: "job_ocr_invoice", expertId: "u_expert4", rate: 2500, eta: "18 ngày", status: "accepted", score: 91, createdAt: "2026-06-22", coverLetter: "Tôi chuyên về OCR và hậu xử lý tiếng Việt. Dự án sẽ gồm baseline PaddleOCR, fine-tune TrOCR và API trích xuất field. Tôi sẽ cung cấp bộ test cho hóa đơn scan mờ và có dấu mộc." },
  { id: "prop_004", jobId: "job_face_attendance", expertId: "u_expert2", rate: 4650, eta: "32 ngày", status: "accepted", score: 94, createdAt: "2026-06-26", coverLetter: "Chuyên về Computer Vision cho nhà máy sản xuất — đã triển khai tại 2 nhà máy ở Bình Dương và Long An. Thời gian phát hiện lỗi < 50ms/frame. Có thể demo live proof-of-concept trong tuần đầu." },
  { id: "prop_005", jobId: "job_social_agent", expertId: "u_expert5", rate: 1600, eta: "12 ngày", status: "accepted", score: 90, createdAt: "2026-06-23", coverLetter: "Tôi đã làm agent lên lịch nội dung cho 4 SME, có workflow duyệt trước khi đăng và logging đầy đủ. Có thể tích hợp Meta API + Canva template để team marketing chỉ cần review nội dung." },
  { id: "prop_006", jobId: "job_logistics_chatbot", expertId: "u_expert5", rate: 4100, eta: "28 ngày", status: "sent", score: 83, createdAt: "2026-06-21", coverLetter: "Tôi mạnh về automation và webhook Zalo/CRM. Giải pháp đề xuất gồm chatbot phân tuyến, fallback human agent, dashboard intent và retry queue khi ERP lỗi." },
  { id: "prop_007", jobId: "job_sales_insight", expertId: "u_expert3", rate: 3700, eta: "22 ngày", status: "sent", score: 82, createdAt: "2026-06-24", coverLetter: "Tôi có kinh nghiệm xây dashboard dữ liệu bán hàng, tracking metric và pipeline tự động. Sẽ triển khai dashboard kèm AI summary hằng ngày và cảnh báo bất thường qua email." },
  { id: "prop_008", jobId: "job_mlops_pipeline", expertId: "u_expert3", rate: 5000, eta: "25 ngày", status: "shortlisted", score: 96, createdAt: "2026-06-28", coverLetter: "Tôi chuyên MLOps với MLflow, DVC, GitHub Actions và Docker. Sẽ audit repo hiện tại, chuẩn hóa pipeline train/deploy và bàn giao runbook rollback cho team AI 10 người." },
  { id: "prop_009", jobId: "job_ner_dataset", expertId: "u_expert4", rate: 1350, eta: "11 ngày", status: "sent", score: 89, createdAt: "2026-06-29", coverLetter: "Tôi từng xây guideline NER tiếng Việt và quản lý QA labeling bằng Doccano/Label Studio. Tôi sẽ thiết kế schema entity, sample review và script kiểm tra conflict giữa annotator." },
  { id: "prop_010", jobId: "job_face_attendance", expertId: "u_expert3", rate: 4550, eta: "35 ngày", status: "rejected", score: 78, createdAt: "2026-06-26", coverLetter: "Tôi có thể hỗ trợ phần deployment và monitoring cho model CV, đặc biệt là logging trên edge device. Tuy nhiên phần training face model sẽ cần phối hợp thêm với CV specialist." },
  { id: "prop_011", jobId: "job_ecom_ai", expertId: "u_expert5", rate: 3000, eta: "24 ngày", status: "sent", score: 84, createdAt: "2026-06-19", coverLetter: "Tôi có kinh nghiệm tích hợp chatbot và workflow marketing automation cho shop online. Có thể kết hợp recommendation cơ bản, chatbot tư vấn và chiến dịch remarketing theo lịch sử mua hàng." },
  { id: "prop_012", jobId: "job_fraud_ml", expertId: "u_expert3", rate: 8300, eta: "7 tuần", status: "sent", score: 88, createdAt: "2026-06-21", coverLetter: "Tôi từng setup realtime monitoring với Kafka/Redis/Grafana. Giải pháp đề xuất gồm baseline XGBoost, feature drift dashboard và rule engine fallback để giảm false positive." },
  { id: "prop_013", jobId: "job_hr_chatbot", expertId: "u_expert", rate: 3400, eta: "20 ngày", status: "sent", score: 87, createdAt: "2026-06-30", coverLetter: "Tôi có kinh nghiệm xây trợ lý đọc PDF và hỏi đáp theo JD. Sẽ bổ sung guardrails để giảm bias, lưu audit trail và tạo bản tóm tắt ứng viên cho HR review." },
  { id: "prop_014", jobId: "job_ocr_invoice", expertId: "u_expert2", rate: 2650, eta: "20 ngày", status: "sent", score: 80, createdAt: "2026-06-22", coverLetter: "Tôi mạnh về image preprocessing, deskew, denoise và pipeline OCR cho ảnh scan. Có thể phối hợp fine-tune OCR và tối ưu inference server." },
  { id: "prop_015", jobId: "job_plant_mobile", expertId: "u_expert2", rate: 3900, eta: "30 ngày", status: "accepted", score: 92, createdAt: "2026-06-16", coverLetter: "Tôi đã triển khai model phân loại hình ảnh trên mobile bằng EfficientNet/TensorFlow Lite. Có thể tối ưu model để chạy nhanh, đồng thời gửi ảnh khó về server để cải thiện dataset." },
];

export const demoContracts: Contract[] = [
  { id: "ctr_logistics_rag", jobId: "job_logistics_chatbot", proposalId: "prop_001", clientId: "u_client3", expertId: "u_expert", title: "RAG Chatbot logistics", status: "active", escrow: 4300, progress: 65, privacy: "private_delivery", startedAt: "2026-06-22", endDate: "2026-07-27" },
  { id: "ctr_fashion_ai", jobId: "job_ecom_ai", proposalId: "prop_002", clientId: "u_client2", expertId: "u_expert2", title: "Website bán thời trang AI", status: "active", escrow: 3200, progress: 30, privacy: "standard", startedAt: "2026-06-24", endDate: "2026-07-24" },
  { id: "ctr_ocr_vn", jobId: "job_ocr_invoice", proposalId: "prop_003", clientId: "u_client", expertId: "u_expert4", title: "OCR hóa đơn tiếng Việt", status: "completed", escrow: 2500, progress: 100, privacy: "standard", startedAt: "2026-06-01", completedAt: "2026-06-24", endDate: "2026-06-24" },
  { id: "ctr_face_factory", jobId: "job_face_attendance", proposalId: "prop_004", clientId: "u_client3", expertId: "u_expert2", title: "Computer Vision chấm công", status: "disputed", escrow: 4650, progress: 55, privacy: "private_delivery", startedAt: "2026-06-18", endDate: "2026-07-23" },
  { id: "ctr_social_agent", jobId: "job_social_agent", proposalId: "prop_005", clientId: "u_client2", expertId: "u_expert5", title: "AI Agent social media", status: "active", escrow: 1600, progress: 80, privacy: "standard", startedAt: "2026-06-24", endDate: "2026-07-08" },
];

export const demoMilestones: Milestone[] = [
  { id: "ms_log_1", contractId: "ctr_logistics_rag", title: "Khảo sát API ERP & thiết kế intent", amount: 900, dueDate: "2026-06-28", status: "approved", deliverable: "Tài liệu kiến trúc, map intent, checklist bảo mật.", paidAt: "2026-06-28" },
  { id: "ms_log_2", contractId: "ctr_logistics_rag", title: "Prototype RAG + Zalo OA webhook", amount: 1800, dueDate: "2026-07-06", status: "submitted", deliverable: "Demo chatbot, eval report và log webhook staging." },
  { id: "ms_log_3", contractId: "ctr_logistics_rag", title: "Handover production & dashboard CSKH", amount: 1600, dueDate: "2026-07-18", status: "pending" as any },
  { id: "ms_fashion_1", contractId: "ctr_fashion_ai", title: "UI storefront + catalog MongoDB", amount: 800, dueDate: "2026-06-30", status: "approved", deliverable: "Next.js storefront, schema sản phẩm, import mẫu.", paidAt: "2026-06-30" },
  { id: "ms_fashion_2", contractId: "ctr_fashion_ai", title: "Recommendation engine outfit", amount: 1400, dueDate: "2026-07-10", status: "in_progress" },
  { id: "ms_fashion_3", contractId: "ctr_fashion_ai", title: "Chatbot tư vấn & analytics", amount: 1000, dueDate: "2026-07-20", status: "planned" },
  { id: "ms_ocr_1", contractId: "ctr_ocr_vn", title: "Dataset hóa đơn & preprocessing", amount: 700, dueDate: "2026-06-08", status: "approved", deliverable: "Dataset, script deskew/denoise.", paidAt: "2026-06-08" },
  { id: "ms_ocr_2", contractId: "ctr_ocr_vn", title: "Fine-tune OCR và field extraction", amount: 1000, dueDate: "2026-06-18", status: "approved", deliverable: "Checkpoint, API extract fields, report accuracy.", paidAt: "2026-06-18" },
  { id: "ms_ocr_3", contractId: "ctr_ocr_vn", title: "Đóng gói FastAPI & tài liệu", amount: 800, dueDate: "2026-06-24", status: "approved", deliverable: "Docker image, API docs, hướng dẫn deploy.", paidAt: "2026-06-24" },
  { id: "ms_face_1", contractId: "ctr_face_factory", title: "POC camera RTSP và enrollment", amount: 1200, dueDate: "2026-06-25", status: "approved", deliverable: "POC video và enrollment flow.", paidAt: "2026-06-25" },
  { id: "ms_face_2", contractId: "ctr_face_factory", title: "Anti-spoofing & report accuracy", amount: 1900, dueDate: "2026-07-05", status: "change_requested", changeRequest: "Cần bổ sung kết quả với ánh sáng yếu và khẩu trang." },
  { id: "ms_face_3", contractId: "ctr_face_factory", title: "Tích hợp HRM & bàn giao", amount: 1550, dueDate: "2026-07-18", status: "planned" },
  { id: "ms_social_1", contractId: "ctr_social_agent", title: "Kịch bản agent và lịch nội dung", amount: 400, dueDate: "2026-06-28", status: "approved", deliverable: "Prompt pack, content calendar, approval flow.", paidAt: "2026-06-28" },
  { id: "ms_social_2", contractId: "ctr_social_agent", title: "Tích hợp Meta API + Canva template", amount: 700, dueDate: "2026-07-03", status: "submitted", deliverable: "Staging agent, Canva template mapping, log đăng bài." },
  { id: "ms_social_3", contractId: "ctr_social_agent", title: "Monitoring và handover", amount: 500, dueDate: "2026-07-08", status: "planned" },
];

export const demoTransactions: Transaction[] = [
  { id: "txn_001", userId: "u_client3", contractId: "ctr_logistics_rag", type: "escrow", amount: 4300, status: "success", createdAt: "2026-06-22", note: "Nạp escrow cho RAG logistics" },
  { id: "txn_002", userId: "u_expert", contractId: "ctr_logistics_rag", milestoneId: "ms_log_1", type: "release", amount: 900, status: "success", createdAt: "2026-06-28", note: "Giải ngân milestone khảo sát API" },
  { id: "txn_003", userId: "u_client2", contractId: "ctr_fashion_ai", type: "escrow", amount: 3200, status: "success", createdAt: "2026-06-24", note: "Nạp escrow website thời trang AI" },
  { id: "txn_004", userId: "u_expert2", contractId: "ctr_fashion_ai", milestoneId: "ms_fashion_1", type: "release", amount: 800, status: "success", createdAt: "2026-06-30", note: "Giải ngân storefront" },
  { id: "txn_005", userId: "u_client", contractId: "ctr_ocr_vn", type: "escrow", amount: 2500, status: "success", createdAt: "2026-06-01", note: "Nạp escrow OCR" },
  { id: "txn_006", userId: "u_expert4", contractId: "ctr_ocr_vn", milestoneId: "ms_ocr_1", type: "release", amount: 700, status: "success", createdAt: "2026-06-08", note: "Giải ngân dataset OCR" },
  { id: "txn_007", userId: "u_expert4", contractId: "ctr_ocr_vn", milestoneId: "ms_ocr_2", type: "release", amount: 1000, status: "success", createdAt: "2026-06-18", note: "Giải ngân fine-tune OCR" },
  { id: "txn_008", userId: "u_expert4", contractId: "ctr_ocr_vn", milestoneId: "ms_ocr_3", type: "release", amount: 800, status: "success", createdAt: "2026-06-24", note: "Giải ngân API docs" },
  { id: "txn_009", userId: "u_client3", contractId: "ctr_face_factory", type: "escrow", amount: 4650, status: "success", createdAt: "2026-06-18", note: "Nạp escrow chấm công CV" },
  { id: "txn_010", userId: "u_expert2", contractId: "ctr_face_factory", milestoneId: "ms_face_1", type: "release", amount: 1200, status: "success", createdAt: "2026-06-25", note: "Giải ngân POC camera" },
  { id: "txn_011", userId: "u_client2", contractId: "ctr_social_agent", type: "escrow", amount: 1600, status: "success", createdAt: "2026-06-24", note: "Nạp escrow social agent" },
  { id: "txn_012", userId: "u_expert5", contractId: "ctr_social_agent", milestoneId: "ms_social_1", type: "release", amount: 400, status: "success", createdAt: "2026-06-28", note: "Giải ngân kịch bản agent" },
  { id: "txn_013", userId: "u_expert", type: "withdrawal", amount: 500, status: "pending", createdAt: "2026-06-29", note: "Rút tiền về ngân hàng" },
  { id: "txn_014", userId: "u_expert2", type: "withdrawal", amount: 600, status: "success", createdAt: "2026-06-30", note: "Rút tiền hoàn tất" },
  { id: "txn_015", userId: "u_client3", contractId: "ctr_face_factory", type: "refund", amount: 350, status: "success", createdAt: "2026-07-01", note: "Hoàn tiền tạm do dispute" },
  { id: "txn_016", userId: "u_expert2", contractId: "ctr_face_factory", type: "fee", amount: 90, status: "success", createdAt: "2026-07-01", note: "Phí nền tảng sau dispute" },
  { id: "txn_017", userId: "u_enterprise", type: "escrow", amount: 1800, status: "pending", createdAt: "2026-06-27", note: "Dự kiến escrow MLOps" },
  { id: "txn_018", userId: "u_client", type: "refund", amount: 120, status: "success", createdAt: "2026-06-26", note: "Hoàn phí kiểm thử" },
  { id: "txn_019", userId: "u_expert5", contractId: "ctr_social_agent", milestoneId: "ms_social_2", type: "release", amount: 700, status: "pending", createdAt: "2026-07-01", note: "Chờ duyệt Meta API" },
  { id: "txn_020", userId: "u_admin", type: "fee", amount: 220, status: "success", createdAt: "2026-07-01", note: "Doanh thu nền tảng" },
];

export const demoDisputes: Dispute[] = [
  { id: "dr_face_001", contractId: "ctr_face_factory", openedBy: "u_client3", reason: "Accuracy khi ánh sáng yếu chưa đạt cam kết nghiệm thu, cần bổ sung bằng chứng trước khi release milestone 2.", evidence: ["night-shift-samples.zip", "accuracy-report-v2.pdf", "chat-log.txt"], status: "mediation", decision: "Admin yêu cầu Expert nộp benchmark bổ sung trong 24h." },
  { id: "dr_social_002", contractId: "ctr_social_agent", openedBy: "u_client2", reason: "Cần xác nhận quyền truy cập Meta API và log đăng bài thử nghiệm.", evidence: ["meta-permission.png"], status: "collecting_evidence" },
];

export const demoNotifications: Notification[] = [
  { id: "noti_001", userId: "u_client3", title: "Expert đã nộp milestone", body: "An Trần đã nộp Prototype RAG + Zalo OA webhook — vui lòng kiểm tra và duyệt.", tone: "info", read: false, createdAt: "2026-07-01 08:30", link: "/client/contracts/ctr_logistics_rag", entityType: "milestone", entityId: "ms_log_2" },
  { id: "noti_002", userId: "u_expert", title: "Milestone được duyệt", body: "Client đã duyệt khảo sát API — $900 đã được giải ngân vào ví của bạn.", tone: "success", read: false, createdAt: "2026-06-28 16:00", link: "/expert/wallet", entityType: "transaction", entityId: "txn_002" },
  { id: "noti_003", userId: "u_admin", title: "Tranh chấp mới", body: "Contract Computer Vision chấm công đang chờ xử lý mediation.", tone: "warning", read: false, createdAt: "2026-07-01 09:00", link: "/admin/disputes", entityType: "dispute", entityId: "dr_face_001" },
  { id: "noti_004", userId: "u_enterprise", title: "Job cần phê duyệt", body: "Hệ thống phát hiện gian lận giao dịch real-time bằng ML đang chờ approval.", tone: "warning", read: false, createdAt: "2026-06-20 10:00", link: "/enterprise/approval", entityType: "job", entityId: "job_fraud_ml" },
  { id: "noti_005", userId: "u_client2", title: "Proposal mới", body: "Nguyễn Linh gửi đơn cho website bán hàng thời trang tích hợp AI.", tone: "info", read: false, createdAt: "2026-06-19 13:12", link: "/client/applicants", entityType: "proposal", entityId: "prop_002" },
  { id: "noti_006", userId: "u_expert2", title: "Hợp đồng mới", body: "Website bán thời trang AI đã bắt đầu, escrow đã được giữ.", tone: "success", read: false, createdAt: "2026-06-24 11:20", link: "/expert/contracts/ctr_fashion_ai", entityType: "contract", entityId: "ctr_fashion_ai" },
  { id: "noti_007", userId: "u_expert4", title: "Đánh giá 5 sao", body: "Client đã đánh giá tích cực dự án OCR hóa đơn tiếng Việt.", tone: "success", read: true, createdAt: "2026-06-25 09:15", link: "/expert/reviews", entityType: "review", entityId: "rev_001" },
  { id: "noti_008", userId: "u_client", title: "Contract hoàn tất", body: "OCR hóa đơn tiếng Việt đã hoàn tất 100% milestone.", tone: "success", read: true, createdAt: "2026-06-24 18:20", link: "/client/contracts/ctr_ocr_vn", entityType: "contract", entityId: "ctr_ocr_vn" },
  { id: "noti_009", userId: "u_expert3", title: "Chờ xác minh hồ sơ", body: "Admin đang kiểm tra portfolio MLOps của bạn.", tone: "info", read: false, createdAt: "2026-06-30 10:30", link: "/expert/profile", entityType: "user", entityId: "u_expert3" },
  { id: "noti_010", userId: "u_admin", title: "Expert chờ xác minh", body: "Trần Quang Huy cần duyệt badge MLOps.", tone: "warning", read: false, createdAt: "2026-06-30 10:31", link: "/admin/verifications", entityType: "user", entityId: "u_expert3" },
  { id: "noti_011", userId: "u_client3", title: "Có tin nhắn mới", body: "Expert hỏi thêm ảnh mẫu có con dấu để cải thiện OCR/CV.", tone: "info", read: false, createdAt: "2026-07-01 10:00", link: "/client/contracts/ctr_face_factory", entityType: "message", entityId: "msg_010" },
  { id: "noti_012", userId: "u_expert5", title: "Milestone đang review", body: "Meta API + Canva template đã được Client mở review.", tone: "info", read: false, createdAt: "2026-07-01 10:05", link: "/expert/contracts/ctr_social_agent", entityType: "milestone", entityId: "ms_social_2" },
  { id: "noti_013", userId: "u_client2", title: "Escrow đã giữ", body: "Hợp đồng AI Agent social media đã giữ $1,600 trong escrow.", tone: "success", read: true, createdAt: "2026-06-24 12:00", link: "/client/wallet", entityType: "transaction", entityId: "txn_011" },
  { id: "noti_014", userId: "u_enterprise", title: "Analytics cập nhật", body: "Chi tiêu AI tháng này đã vượt $12,000 — xem breakdown theo category.", tone: "info", read: false, createdAt: "2026-07-01 07:30", link: "/enterprise/analytics", entityType: "analytics", entityId: "ent_nova" },
  { id: "noti_015", userId: "u_admin", title: "Thanh toán cần đối soát", body: "Một giao dịch withdrawal của Expert đang pending.", tone: "warning", read: false, createdAt: "2026-07-01 06:45", link: "/admin/payments", entityType: "transaction", entityId: "txn_013" },
];

export const demoReviews: Review[] = [
  { id: "rev_001", contractId: "ctr_ocr_vn", fromUserId: "u_client", toUserId: "u_expert4", rating: 5, body: "An làm việc rất chuyên nghiệp, code sạch, có document đầy đủ. Chỉ hơi chậm ở milestone 2 nhưng chất lượng bù đắp hoàn toàn. Sẽ tiếp tục thuê cho dự án tiếp theo.", reply: "Cảm ơn anh/chị, em đã bổ sung thêm checklist deploy để team dễ vận hành.", communicationRating: 5, qualityRating: 5, timelinessRating: 4, createdAt: "2026-06-25" },
  { id: "rev_002", contractId: "ctr_fashion_ai", fromUserId: "u_client2", toUserId: "u_expert2", rating: 5, body: "Linh giao hàng đúng hạn, model accuracy tốt hơn benchmark đề ra. Giao tiếp rõ ràng, proactive cập nhật tiến độ mỗi ngày. Highly recommend!", communicationRating: 5, qualityRating: 5, timelinessRating: 5, createdAt: "2026-06-30" },
  { id: "rev_003", contractId: "ctr_face_factory", fromUserId: "u_client3", toUserId: "u_expert2", rating: 4, body: "Chất lượng ổn nhưng cần nhiều vòng revise hơn mong đợi (3 lần thay vì 1). Kết quả cuối cùng đạt yêu cầu.", communicationRating: 4, qualityRating: 4, timelinessRating: 3, createdAt: "2026-06-29" },
  { id: "rev_004", contractId: "ctr_logistics_rag", fromUserId: "u_client3", toUserId: "u_expert", rating: 5, body: "Kiến trúc RAG rõ ràng, có citation và guardrails. Phần handoff rất chuyên nghiệp.", communicationRating: 5, qualityRating: 5, timelinessRating: 5, createdAt: "2026-06-28" },
  { id: "rev_005", contractId: "ctr_social_agent", fromUserId: "u_client2", toUserId: "u_expert5", rating: 4, body: "Agent hoạt động tốt, cần thêm log lỗi rõ hơn khi Meta API rate limit.", communicationRating: 4, qualityRating: 4, timelinessRating: 4, createdAt: "2026-07-01" },
  { id: "rev_006", contractId: "ctr_ocr_vn", fromUserId: "u_expert4", toUserId: "u_client", rating: 5, body: "Client phản hồi nhanh, cung cấp dataset đầy đủ và nghiệm thu rõ ràng.", communicationRating: 5, qualityRating: 5, timelinessRating: 5, createdAt: "2026-06-25" },
  { id: "rev_007", contractId: "ctr_logistics_rag", fromUserId: "u_expert", toUserId: "u_client3", rating: 5, body: "Đội logistics có API docs tốt và feedback rõ trong từng milestone.", communicationRating: 5, qualityRating: 5, timelinessRating: 5, createdAt: "2026-06-29" },
  { id: "rev_008", contractId: "ctr_fashion_ai", fromUserId: "u_expert2", toUserId: "u_client2", rating: 4, body: "Yêu cầu thay đổi nhiều nhưng hợp lý, sản phẩm cuối cùng có scope rõ.", communicationRating: 4, qualityRating: 4, timelinessRating: 4, createdAt: "2026-06-30" },
];

export const demoMessages: Message[] = [
  { id: "msg_001", contractId: "ctr_ocr_vn", senderId: "u_client", body: "Anh ơi, phần OCR với hóa đơn VAT dạng scan mờ thì accuracy đang bao nhiêu %?", kind: "text", createdAt: "2026-06-18 09:10" },
  { id: "msg_002", contractId: "ctr_ocr_vn", senderId: "u_expert4", body: "Hiện đang 87% trên test set, em đang augment thêm ảnh mờ để improve. Chiều mai sẽ có kết quả mới.", kind: "text", createdAt: "2026-06-18 09:14" },
  { id: "msg_003", contractId: "ctr_ocr_vn", senderId: "u_client", body: "Tốt, anh cần thêm support cho hóa đơn có seal/con dấu nhé.", kind: "text", createdAt: "2026-06-18 09:20" },
  { id: "msg_004", contractId: "ctr_ocr_vn", senderId: "u_expert4", body: "Dạ, em sẽ thêm vào sprint 2. Có thể gửi em 20-30 ảnh mẫu với con dấu để train không ạ?", kind: "text", createdAt: "2026-06-18 09:23" },
  { id: "msg_005", contractId: "ctr_logistics_rag", senderId: "u_client3", body: "Phần tra cứu đơn hàng qua Zalo OA cần trả lời trong dưới 3 giây nhé An.", kind: "text", createdAt: "2026-07-01 08:00" },
  { id: "msg_006", contractId: "ctr_logistics_rag", senderId: "u_expert", body: "Em đã cache kết quả tracking thường dùng và fallback khi ERP chậm. Demo hiện đang ~1.4s/query.", kind: "text", createdAt: "2026-07-01 08:04" },
  { id: "msg_007", contractId: "ctr_logistics_rag", senderId: "u_expert", body: "const retriever = vectorStore.asRetriever({ k: 6, filter: { tenantId, access: user.scope } });", kind: "code", createdAt: "2026-07-01 08:07" },
  { id: "msg_008", contractId: "ctr_logistics_rag", senderId: "u_admin", body: "Cảnh báo kiểm duyệt: không chia sẻ token ERP hoặc private key trong chat.", kind: "warning", createdAt: "2026-07-01 08:10" },
  { id: "msg_009", contractId: "ctr_face_factory", senderId: "u_client3", body: "Ca đêm ánh sáng yếu nhận diện sai nhiều, em kiểm tra lại giúp chị.", kind: "text", createdAt: "2026-06-30 20:15" },
  { id: "msg_010", contractId: "ctr_face_factory", senderId: "u_expert2", body: "Dạ, em cần thêm 30 ảnh mẫu ca đêm và ảnh có khẩu trang để augment. Em sẽ gửi benchmark mới trong 24h.", kind: "text", createdAt: "2026-06-30 20:20" },
  { id: "msg_011", contractId: "ctr_face_factory", senderId: "u_client3", body: "Chị đã upload file night-shift-samples.zip vào workspace.", kind: "file", createdAt: "2026-06-30 20:40" },
  { id: "msg_012", contractId: "ctr_fashion_ai", senderId: "u_client2", body: "Linh ơi, outfit recommendation có thể ưu tiên hàng tồn kho cao không?", kind: "text", createdAt: "2026-06-29 14:00" },
  { id: "msg_013", contractId: "ctr_fashion_ai", senderId: "u_expert2", body: "Có anh, em sẽ thêm weight inventory_score vào ranking để đẩy sản phẩm tồn kho nhưng vẫn giữ relevance.", kind: "text", createdAt: "2026-06-29 14:05" },
  { id: "msg_014", contractId: "ctr_social_agent", senderId: "u_client2", body: "Agent phải dừng đăng nếu caption chứa từ khóa giảm giá quá mức nhé.", kind: "text", createdAt: "2026-07-01 10:00" },
  { id: "msg_015", contractId: "ctr_social_agent", senderId: "u_expert5", body: "Dạ, em thêm moderation rule trước khi gọi Meta API. Caption fail rule sẽ chuyển sang trạng thái cần duyệt thủ công.", kind: "text", createdAt: "2026-07-01 10:02" },
  { id: "msg_016", contractId: "ctr_social_agent", senderId: "u_expert5", body: "if (blockedKeywords.some((kw) => caption.includes(kw))) return { status: 'needs_review' };", kind: "code", createdAt: "2026-07-01 10:03" },
  { id: "msg_017", contractId: "ctr_logistics_rag", senderId: "u_client3", body: "Có thể thêm intent khiếu nại giao hàng chậm vào ngày mai không?", kind: "text", createdAt: "2026-07-01 11:00" },
  { id: "msg_018", contractId: "ctr_logistics_rag", senderId: "u_expert", body: "Được ạ, em sẽ thêm intent đó vào test set và cập nhật prompt routing.", kind: "text", createdAt: "2026-07-01 11:03" },
  { id: "msg_019", contractId: "ctr_face_factory", senderId: "u_admin", body: "Mediation note: Expert cần nộp benchmark bổ sung trước 18:00 hôm nay.", kind: "ai", createdAt: "2026-07-01 09:30" },
  { id: "msg_020", contractId: "ctr_fashion_ai", senderId: "u_expert2", body: "Em đã push bản demo style matching, client có thể test theo user persona trong file README.", kind: "text", createdAt: "2026-07-01 12:00" },
];

export const demoServices: Service[] = [
  { id: "svc_rag", slug: "ai-custom-rag-chatbot", title: "AI Custom RAG Chatbot", description: "Chatbot RAG riêng tư cho tài liệu doanh nghiệp, có citation, đánh giá recall và guardrails.", priceFrom: 2800, delivery: "14-21 ngày", tags: ["RAG", "LLM", "Security", "Vector DB"], expertId: "u_expert" },
  { id: "svc_cv", slug: "computer-vision-inspection", title: "Computer Vision Inspection", description: "Prototype phát hiện lỗi sản xuất bằng YOLO/OpenCV, có data audit và dashboard.", priceFrom: 3600, delivery: "21-35 ngày", tags: ["CV", "YOLO", "PyTorch"], expertId: "u_expert2" },
  { id: "svc_ops", slug: "mlops-ai-agent-ci-cd", title: "MLOps for AI Agents", description: "Prompt versioning, eval runner, CI/CD, rollback và audit logs cho AI Agent.", priceFrom: 3200, delivery: "18-28 ngày", tags: ["MLOps", "CI/CD", "Eval", "Observability"], expertId: "u_expert3" },
  { id: "svc_agent", slug: "ai-agent-automation", title: "AI Agent Automation", description: "Tự động hóa quy trình SME bằng LangGraph, n8n, Zapier và Node.js.", priceFrom: 1800, delivery: "10-18 ngày", tags: ["Agent", "Automation", "LangGraph"], expertId: "u_expert5" },
];

export const demoAuditLogs: AuditLog[] = [
  { id: "aud_001", actorId: "u_admin", action: "verification.approved", targetId: "u_expert", metadata: "Duyệt badge RAG/LLM Expert", createdAt: "2026-06-20 09:00" },
  { id: "aud_002", actorId: "u_admin", action: "verification.approved", targetId: "u_expert2", metadata: "Duyệt badge Computer Vision", createdAt: "2026-06-21 10:15" },
  { id: "aud_003", actorId: "u_admin", action: "verification.pending", targetId: "u_expert3", metadata: "Chờ bổ sung portfolio MLOps", createdAt: "2026-06-22 11:30" },
  { id: "aud_004", actorId: "u_admin", action: "user.block", targetId: "u_spam_001", metadata: "Khóa tài khoản spam proposal", createdAt: "2026-06-23 14:00" },
  { id: "aud_005", actorId: "u_admin", action: "dispute.mediation", targetId: "dr_face_001", metadata: "Yêu cầu benchmark ca đêm", createdAt: "2026-06-30 21:00" },
  { id: "aud_006", actorId: "u_enterprise", action: "enterprise.job.pending", targetId: "job_fraud_ml", metadata: "Chờ duyệt dữ liệu nhạy cảm", createdAt: "2026-06-20 10:00" },
  { id: "aud_007", actorId: "u_admin", action: "platform.settings.update", targetId: "commission", metadata: "Commission 10%", createdAt: "2026-06-25 08:00" },
  { id: "aud_008", actorId: "u_admin", action: "payment.withdrawal.review", targetId: "txn_013", metadata: "Withdrawal pending", createdAt: "2026-06-29 16:00" },
  { id: "aud_009", actorId: "u_admin", action: "moderation.keyword.update", targetId: "policy", metadata: "Thêm từ khóa cấm API key/token", createdAt: "2026-06-27 15:00" },
  { id: "aud_010", actorId: "u_admin", action: "seed.platform_ready", targetId: "system", metadata: "AITasker demo data 12 users / 20 jobs ready", createdAt: "2026-07-01 07:00" },
];
