import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { CreateDisputeDto } from './dto/create-dispute.dto';
import { UpdateDisputeDto } from './dto/update-dispute.dto';
import { Dispute, DisputeDocument } from './dispute.schema';
import { Contract, ContractDocument } from '../contracts/contract.schema';
import { Transaction, TransactionDocument } from '../transactions/transaction.schema';
import { Notification, NotificationDocument } from '../notifications/notification.schema';
import { User, UserDocument } from '../users/user.schema';
import { toDispute } from '../common/mongo-mappers';
@Injectable()
export class DisputesService { constructor(@InjectModel(Dispute.name) private model: Model<DisputeDocument>, @InjectModel(Contract.name) private contractModel: Model<ContractDocument>, @InjectModel(Transaction.name) private transactionModel: Model<TransactionDocument>, @InjectModel(Notification.name) private notificationModel: Model<NotificationDocument>, @InjectModel(User.name) private userModel: Model<UserDocument>) {} async findAll() { return (await this.model.find().sort({ createdAt: -1 })).map(toDispute); } async create(dto: CreateDisputeDto) { const dispute = await this.model.create({ ...dto, status: 'collecting_evidence' }); const c = await this.contractModel.findById(dto.contractId); if (c) { c.status = 'disputed'; await c.save(); await this.notificationModel.create([{ userId: 'u_admin', title: 'Tranh chấp mới', body: String(dispute._id), tone: 'warning', entityType: 'dispute', entityId: String(dispute._id) }, { userId: c.clientId, title: 'Đã mở tranh chấp', body: dto.reason, tone: 'warning', entityType: 'dispute', entityId: String(dispute._id) }, { userId: c.expertId, title: 'Đã mở tranh chấp', body: dto.reason, tone: 'warning', entityType: 'dispute', entityId: String(dispute._id) }]); } return toDispute(dispute); } async update(id: string, dto: UpdateDisputeDto & { resolution?: string }) { const d = await this.model.findByIdAndUpdate(id, dto, { new: true }); if (!d) throw new NotFoundException('Dispute not found'); const c = await this.contractModel.findById(d.contractId); if (c && dto.status === 'enforced') { c.status = 'completed'; c.progress = 100; c.completedAt = new Date(); await c.save(); if (dto.resolution === 'refund_client') { const amount = Math.round(c.escrowAmount * 0.3); await this.transactionModel.create({ userId: c.clientId, contractId: String(c._id), type: 'refund', amount, status: 'completed', note: 'Admin dispute decision: refund client' }); await this.userModel.findByIdAndUpdate(c.clientId, { $inc: { walletBalance: amount } }); } else { const amount = Math.round(c.escrowAmount * 0.7); await this.transactionModel.create({ userId: c.expertId, contractId: String(c._id), type: 'dispute_resolution', amount, status: 'completed', note: 'Admin dispute decision: release expert' }); await this.userModel.findByIdAndUpdate(c.expertId, { $inc: { walletBalance: amount, totalEarnings: amount } }); } await this.notificationModel.create([{ userId: c.clientId, title: 'Tranh chấp đã xử lý', body: dto.decision || 'Quyết định đã thực thi', tone: 'success', entityType: 'dispute', entityId: String(d._id) }, { userId: c.expertId, title: 'Tranh chấp đã xử lý', body: dto.decision || 'Quyết định đã thực thi', tone: 'success', entityType: 'dispute', entityId: String(d._id) }]); } return toDispute(d); } }
